### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by DeDuckProject** [hrossman/Patterns-of-covid-19-pandemic-dynamics-following-deployment-of-a-broad-national-immunization-program#1]
![4045ABDC-0196-4939-96D8-5141EEB945E2](https://user-images.githubusercontent.com/10045034/106813611-e7257600-6679-11eb-9846-6adee4283d00.jpeg)

**Comment by hrossman** [comment]
Thanks Iftach!

**Comment by hrossman** [comment]
fixed
